// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vistoria_projeto.Context;

#nullable disable

namespace Vistoria_projeto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117185321_Add_Trabalho")]
    partial class Add_Trabalho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vistoria_projeto.Models.ChecklistVistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcabamentosOk")
                        .HasColumnType("bit");

                    b.Property<bool>("ArmariosBanheiroOk")
                        .HasColumnType("bit");

                    b.Property<bool>("ArmariosCozinhaOk")
                        .HasColumnType("bit");

                    b.Property<string>("AssinadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BoxBomEstado")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChuveiroOk")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EspelhosOk")
                        .HasColumnType("bit");

                    b.Property<bool>("FechadurasOk")
                        .HasColumnType("bit");

                    b.Property<bool>("FogaoIncluido")
                        .HasColumnType("bit");

                    b.Property<bool>("GeladeiraIncluida")
                        .HasColumnType("bit");

                    b.Property<string>("Horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IluminacaoOk")
                        .HasColumnType("bit");

                    b.Property<string>("Imovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InterruptoresOk")
                        .HasColumnType("bit");

                    b.Property<bool>("JanelasVedando")
                        .HasColumnType("bit");

                    b.Property<bool>("LaudoAssinado")
                        .HasColumnType("bit");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PiaBomEstado")
                        .HasColumnType("bit");

                    b.Property<bool>("PinturaBomEstado")
                        .HasColumnType("bit");

                    b.Property<bool>("PisoBomEstado")
                        .HasColumnType("bit");

                    b.Property<bool>("PortasFuncionando")
                        .HasColumnType("bit");

                    b.Property<bool>("QuadroLuzOk")
                        .HasColumnType("bit");

                    b.Property<bool>("RalosDesentupidos")
                        .HasColumnType("bit");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RodapesConservados")
                        .HasColumnType("bit");

                    b.Property<bool>("SemInfiltracoes")
                        .HasColumnType("bit");

                    b.Property<bool>("SemManchas")
                        .HasColumnType("bit");

                    b.Property<bool>("SemRachaduras")
                        .HasColumnType("bit");

                    b.Property<bool>("SemTrincas")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TomadasFuncionando")
                        .HasColumnType("bit");

                    b.Property<bool>("TorneirasSemVazamento")
                        .HasColumnType("bit");

                    b.Property<bool>("VasoSanitarioOk")
                        .HasColumnType("bit");

                    b.Property<bool>("VidrosIntactos")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChecklistsVistorias");
                });
#pragma warning restore 612, 618
        }
    }
}
